### ISSUE TITLE
Add doctrine/mongo-odm dependency for development

### ISSUE THREAD

**Issue by core23** [sonata-project/exporter#113]
We can't require the dependency now, because there is no mongo db driver for PHP7.

**Comment by Soullivaneuh** [comment]
See also: https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/issues/168

If you want to do some researches... :wink:

**Comment by core23** [comment]
Here is the usage:
https://github.com/sonata-project/exporter/blob/1.x/src/Source/DoctrineODMQuerySourceIterator.php#L14
