### ISSUE TITLE
Add BC way for namespace changes

### ISSUE THREAD

**Issue by core23** [sonata-project/exporter#198]
The namespace will change with the next major release. We should find a way to inform the user, that the namespace will change.

Maybe we could use something like [EasyAdmin](https://github.com/javiereguiluz/EasyAdminBundle) is doing with the legacy folder

**Comment by greg0ire** [comment]
Or maybe use `class_alias`?

**Comment by greg0ire** [comment]
Not sure it can work with a deprecation though...

**Comment by core23** [comment]
Afaik, is using `class_alias` too

**Comment by greg0ire** [comment]
I don't understand how it works O_o https://github.com/javiereguiluz/EasyAdminBundle/blob/master/legacy/Form/Type/EasyAdminDividerType.php what's the point of `if (\false)`?

**Comment by core23** [comment]
Maybe some kind of hack for PHP7?

**Comment by greg0ire** [comment]
From @xabbuh:

> That's for autocompletion in IDEs.
> So that users can still use autocompletion with the legacy class name.

**Comment by greg0ire** [comment]
I will do something minimal that time, with no deprecation.

**Comment by core23** [comment]
Not sure, if we still need this. We already have a stable release with the new namespace.

**Comment by greg0ire** [comment]
yes but it is hard to create code that supports both versions.

**Comment by greg0ire** [comment]
> I will do something minimal that time, with no deprecation.

I ended up adding them anyway, it wasn't too hard.
