### ISSUE TITLE
Unable to register v2 Symfony bundle

### ISSUE THREAD

**Issue by martixy** [sonata-project/exporter#283]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.45.1 3.45.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.14.0 3.14.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.15.0 3.15.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.5  1.1.5  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.1  3.8.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.0.0  2.0.0  Lightweight Exporter library
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.3.1  v3.3.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.4.21 v4.2.2  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.10.0 v1.10.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.10.0 v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.10.0 v1.10.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.2.5  Symfony SwiftmailerBundle
symfony/symfony            v3.4.21 v4.2.2  The Symfony PHP framework

```

#### PHP version

```
$ php -v
PHP 7.2.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Dec  7 2018 08:07:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Zend Server Z-Ray v9.2.0, Copyright (c) 2004-2017, by Zend Technologies
    with blackfire v1.23.1~linux-x64-non_zts72, https://blackfire.io, by Blackfire

```

## Subject

Trying to register the v2 bundle on Sy3.4 at least fails miserably.
There is a note on support for different versions of symfony, but if v2 happens to be incompatible with <Sy4.0 _at least update the damn documentation_ before including a version constraint like `"^1.11.0 || ^2.0"` that forces the update.

## Steps to reproduce
Do something that installs the `Exporter` v2. I ran `composer update` on Sy3.4 (haven't tested on Sy4.0).
Try to register the exporter bundle ->
`new Sonata\Exporter\Bridge\Symfony\Bundle\SonataExporterBundle()`

## Expected results
Seamless update.

## Actual results
Various errors like
`There is no extension able to load the configuration for "sonata_exporter"`
OR
`The service "sonata.admin.admin_exporter" has a dependency on a non-existent service "sonata.exporter.exporter".`
...which boil down to not being able to register the bundle.

**Comment by greg0ire** [comment]
Thanks for reporting this bug, but please keep it civil.

> at least update the damn documentation before including a version constraint like "^1.11.0 || ^2.0" that forces the update.

It does not force the update at all, this would: `^2.0`. The constraint we put allows the update. If you are using the exporter, then you should have a constraint that forces version 1 in your `composer.json` to avoid any BC-breaks. You can use https://github.com/maglnet/ComposerRequireChecker to find other versions constraints you might have forgotten.

**Comment by martixy** [comment]
Sorry. Was having a bad day.

Would a stack trace of the non-existent service help?

**Comment by greg0ire** [comment]
Thanks for apologizing :) In retrospect, I'm not so sure a stack trace will help in this case, since the messages you get seem to point to something not being done, rather that to something attempting to be done and crashing. A micro application that I could clone from Github would be more helpful, because I could debug it.

**Comment by greg0ire** [comment]
I confirm the bugfix, good job! @martixy , please try 2.0.1!

**Comment by martixy** [comment]
Can confirm, bundle registration works correctly now.
Thanks.
