### ISSUE TITLE
Not sure what to pass in DoctrineORMQuerySourceIterator

### ISSUE THREAD

**Issue by babaganoush** [sonata-project/exporter#34]
http://stackoverflow.com/questions/21127154/how-to-export-an-entity-as-a-csv-in-symfony

can anyone help?

**Comment by chalasr** [comment]
I've answered [your question on stackoverflow ](http://stackoverflow.com/a/33844428/4363634) with a working example for your data using the CsvWriter.
I think this issue can be closed
