### ISSUE TITLE
PDF Export Feature

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/exporter#42]
I have seen an example how to export PDF by injecting the `KnpSnappyBundle`:
http://cristian-radulescu.ro/article/add-pdf-export-functionality-in-sonataadminbundle.html

But the tutorial also states that the Sonata way would be to use a `PdfWriter` class.
Are there any plans for such a service?

**Comment by chalasr** [comment]
For a lot of my projects using sonata, I did have to code a custom PDF export functionality, which is generally added as a BATCH action on list views, not in the export section where it should be.
@rande I can work on this feature if you are agree.

**Comment by rande** [comment]
yes, of course.

**Comment by OskarStark** [comment]
:+1:

**Comment by chalasr** [comment]
Ok, I will submit it soon.
Thank's @webdevilopers

**Comment by Soullivaneuh** [comment]
@chalasr Please take in consideration that knp-snappy should be **optional**

The best would be to have a `PdfWriterInterface` and a `KnpSnappyPdfWriter`. So, developpers can write pdf writers with other libraries like dompdf for example.

**Comment by chalasr** [comment]
@Soullivaneuh Ok, I will use this approach . Thanks

**Comment by rande** [comment]
@Soullivaneuh you give too much insight ;)

**Comment by rande** [comment]
Actually a KnpSnappyWriter will do the job too ;)

**Comment by rande** [comment]
Closing this issue, as it not the aim of this library to provide such features. Exporting data into PDF is more about reporting.
