### ISSUE TITLE
Replace Query::iterable with Query::toIterable

### ISSUE THREAD

**Issue by franmomu** [sonata-project/exporter#459]
## Feature Request

[`Query::iterable()` is deprecated (`doctrine/orm`) in favor of `Query::toIterable()`](https://github.com/doctrine/orm/blob/5247c56fce2285ba0b0584cfe9376c68a959d012/UPGRADE.md#deprecated-doctrineormabstractqueryiterator):

https://github.com/sonata-project/exporter/blob/03b219538464e588c978a9a634d568dc8ba77748/src/Source/DoctrineORMQuerySourceIterator.php#L55

The difference is that `toIterable` doesn't return an array, so:

https://github.com/sonata-project/exporter/blob/03b219538464e588c978a9a634d568dc8ba77748/src/Source/DoctrineORMQuerySourceIterator.php#L46

`$current[0]` won't be needed, just `$current`.

Also we're using `IterableResult` which is deprecated (and from `doctrine/orm`), I guess with `\Iterator` will be enough.

https://github.com/sonata-project/exporter/blob/03b219538464e588c978a9a634d568dc8ba77748/src/Source/AbstractPropertySourceIterator.php#L36

**Comment by VincentLanglet** [comment]
Do we have to wait the next major ?

**Comment by VincentLanglet** [comment]
@franmomu `toIterable` returns an iterable when `iterable` returns an `\Iterator`.

Do we have an easy way to transform iterable into an \iterator ?

**Comment by franmomu** [comment]
Maybe with this https://github.com/doctrine/orm/blob/0bcc3ee4e9bde2e7996411d50c4099b4c2e7739d/tests/Doctrine/Tests/IterableTester.php#L34-L37

And then use [\ArrayIterator](https://www.php.net/manual/en/class.arrayiterator.php)

**Comment by davidromani** [comment]
Sorry but I think this merge has caused a side effect that prevents exporting correctly.

In my case, I have these dependencies defined:
```
        "doctrine/annotations": "^1.0",
        "doctrine/common": "^2.13",
        "doctrine/doctrine-bundle": "^2.3",
        "doctrine/doctrine-migrations-bundle": "^2.1",
        "doctrine/orm": "^2.7",
        "sensio/framework-extra-bundle": "^5.5",
        "sonata-project/admin-bundle": "^3.70",
        "sonata-project/doctrine-orm-admin-bundle": "^3.10",
        "sonata-project/user-bundle": "^4.0",
        "stof/doctrine-extensions-bundle": "^1.3",
        "symfony/framework-bundle": "4.4.*",
(and more...)
```

and I get the following error when executing any Sonata export:
```
Attempted to call an undefined method named "toIterable" of class "Doctrine\ORM\Query".
```

I understand that the "toIterable" method is **not** available in my current `doctrine/orm` dependency installed version (2.7.5). This method is only available in a later version (I don't know which one) so I think this dependency requirement must be fixed, rigth?

Can anyone confirm the error? Is there a way to fix it? In my case, I have a couple of projects in production that have stopped exporting correctly due to the same problem.

Thank you very much for your help!

**Comment by VincentLanglet** [comment]
Indeed the method was introduced in 2.8

We need to bump the require-dev https://github.com/sonata-project/exporter/blob/2.x/composer.json#L33
And add a conflict https://github.com/sonata-project/exporter/blob/2.x/composer.json#L26

Can you do the PR @davidromani ?

**Comment by davidromani** [comment]
@VincentLanglet let my try the easiest part... don't know if following PR will be enough to solve it

**Comment by VincentLanglet** [comment]
> @VincentLanglet let my try the easiest part... don't know if following PR will be enough to solve it

I made https://github.com/sonata-project/exporter/pull/533
It wont solve the current version, but the next ones.

Until that you have to stick with the older version of the exporter library or use doctrine/orm >= 2.8

**Comment by davidromani** [comment]
> > @VincentLanglet let my try the easiest part... don't know if following PR will be enough to solve it
> 
> I made #533 It wont solve the current version, but the next ones.
> 
> Until that you have to stick with the older version of the exporter library or use doctrine/orm >= 2.8

Sorry I saw your PR after mine

**Comment by VincentLanglet** [comment]
> Sorry I saw your PR after mine

Don't be. You can either solve the test and I'll approved your and close mine (if you want to be a contributor ^^) or you can close it and I'll wait for approval on mine from others maintainers ;)

**Comment by davidromani** [comment]
I like to contribute if I can help and I've enough time. But in this case I prefer to close my PR, thanks.
