### ISSUE TITLE
Add an explanation of the withBom option utility

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/exporter#487]
We currently have a `withBom` option adding some special chars at the beginning of the CSV file: https://github.com/sonata-project/exporter/blob/487a4f31cebe8f12e4ca8c47099c9ef9230108ce/src/Writer/CsvWriter.php#L111-L113

However, we don't know what is the goal of this option.

It would be great to have one explanation sentence on the documentation and/or a documentation links about it.

**Comment by OskarStark** [comment]
cc @greg0ire

**Comment by greg0ire** [comment]
This was introduced in #53 , @ThibautAlgrin can you please look into this?

BTW I didn't review that PR, but you did @soullivaneuh :stuck_out_tongue: 

More details on what that is can be found here: https://en.wikipedia.org/wiki/Byte_order_mark
