### ISSUE TITLE
Introducing PortPHP: Possible future cooperation

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/exporter#51]
Hey everyone!

Sonata is pretty new to me and I can say I like what I see so far. During browsing the repositories I find this little library. It looks good...but there might be better options.

[PortPHP](https://github.com/portphp) is (going to be) a replacement for [ddeboer/data-import](https://github.com/ddeboer/data-import). It does exactly the same as this library, but probably is a bit more powerful.

Take a look at it, I hope you might be able to use some things from it.

**Comment by greg0ire** [comment]
Side note : I use ddeboer/data-import on a project of mine and find it very powerful already, so I will definitely look into PortPHP in the future.
