### ISSUE TITLE
Export with where clause

### ISSUE THREAD

**Issue by seb2020** [sonata-project/exporter#52]
Hello,

I want to export an entity with a where clause in the SQL. I have this : 

``` php
    $sqlQuery = $em->getRepository('AppBundle:Member')
                ->createQueryBuilder('m')
                ->where('m.association = :id')
               ->setParameter('id', $id)
                ->getQuery()
                ->getSQL(); 
```

But I have this error : 

> SQLSTATE[HY093]: Invalid parameter number: no parameters were bound 

If I remove the where clause, everything work fine. 

What is the correct way for doing that ?

Thanks

**Comment by rande** [comment]
I guess you need to respect method signature:

**Comment by seb2020** [comment]
I have try with this :
    
    $sqlQuery = $em->getRepository('AppBundle:Member')
                ->createQueryBuilder('m')
                ->where('m.association = :id')                
                ->getQuery()
                ->getSQL();
    $sourceIterator = new DoctrineDBALConnectionSourceIterator($doctrineDatabaseConnection, $sqlQuery, array('id', $id));

But now I have this error :
  
    An exception occurred while executing 'SELECT m0_.id AS id0, m0_.name AS name1, m0_.firstname AS firstname2, m0_.birthday AS birthday3, m0_.email AS email4, m0_.phone AS phone5, m0_.address AS address6, m0_.description AS description7, m0_.association_id AS association_id8, m0_.locality_id AS locality_id9 FROM member m0_ WHERE m0_.association_id = ?' with params ["id", "42"]:

SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

**Comment by core23** [comment]
Think you have an error in your last parameter. Should be `array('id' => $id)` @seb2020

**Comment by jordisala1991** [comment]
@core23 pointed out a possible solution. Closing for now, if any of the @sonata-project/contributors or @seb2020 thinks that this should be handled different, please ping me to reopen, or reopen directly.
