### ISSUE TITLE
Issues with the deprecated arguments of the generate() method

### ISSUE THREAD

**Issue by javiereguiluz** [sonata-project/exporter#54]
I'm getting this deprecation message while upgrading a Symfony app to 2.8:

```
The hardcoded value you are using for the $referenceType argument of the 
Symfony\Component\Routing\Generator\UrlGenerator::generate method is
deprecated since version 2.8 and will not be supported anymore in 3.0. 
Use the constants defined in the UrlGeneratorInterface instead.
```

The problem is located here: https://github.com/sonata-project/exporter/blob/master/lib/Exporter/Source/SymfonySitemapSourceIterator.php#L50

**Comment by core23** [comment]
Fixed https://github.com/sonata-project/exporter/commit/474be8b9dbb8ca1c378aa24e701df940a89ec124

**Comment by OskarStark** [comment]
:+1:
