### ISSUE TITLE
Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by nzurita** [sonata-project/exporter#58]
Running this but of code I get an exception when Exporter finds a date in the array.

```php
$source = new ArraySourceIterator($queryFilter->getArrayResult());
$writer = new CsvWriter("data.csv");
Handler::create($source, $writer)->export();
```

> Catchable Fatal Error: Object of class DateTime could not be converted to string

```php
$result = @fputcsv($this->file, $data, $this->delimiter, $this->enclosure);
```
And I have a question: how does the exporter handle entity relations?

**Comment by core23** [comment]
Could you supply more information @nzurita 

Looks like you are using the `SonataAdminBundle`. Can you show your Admin class or a stack trace.

**Comment by nzurita** [comment]
Sorry, this message is too old, I don't keep that code anymore

**Comment by greg0ire** [comment]
Closing then.
