### ISSUE TITLE
Compatibility Doctrine/ORM 2.7

### ISSUE THREAD

**Issue by lebacql** [sonata-project/exporter#645]
![image](https://github.com/sonata-project/exporter/assets/10719771/5dc417e6-66e2-49e8-ac4e-b8f2384d80e5)

https://github.com/sonata-project/exporter/blob/c1aa20bcf556207734df521ce4a54925994760b6/src/Source/DoctrineORMQuerySourceIterator.php#L62

I solved my incompatibility problem by changing the method  ```$this->query->toIterable()``` by ```$this->query->getResult()```

**Comment by VincentLanglet** [comment]
We're having a conflict with doctrine/orm <2.14 so you should not be able to use 2.7
https://github.com/sonata-project/exporter/blame/3.x/composer.json#L55
